### PR TITLE
feat: update example with file templates

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Generator has new way to render multiple files for React renderer. This PR makes changes for related part to show new feature:
- update `template/schemas/schema.js` template,
- update main Readme - remove section about `File` templates and write about tip how to render multiple files.

**Related issue(s)**
See https://github.com/asyncapi/generator/pull/518#issuecomment-788863216

### CODE REVIEW

**Comment by derberg** [comment]
please remove any mention of file templates, except for having it somewhere as the last sentence saying that in Nunjucks it was done through file templates.

my main motivation for this feature was to simplify onboarding on generator and having as less different feature as possible. So they do not have to understand what "file template" is, but they just have an example how they can generate 1:1 file and 1:n files. Please adjust description 🙏🏼

**Comment by magicmatatjahu** [comment]
@derberg Yeah sure, I see your PoV.

**Comment by derberg** [comment]
Thank you @magicmatatjahu same needs to be improved in generator docs imho but I know this is tricky as we do not hide Nunjucks there like here

**Comment by magicmatatjahu** [comment]
@derberg Done :) Yep, we should first rewrite all templates to React and then remove from docs Nunjucks with `File templates`.

**Comment by magicmatatjahu** [comment]
@derberg Done :)

**Review by derberg — DISMISSED** [review]
now it looks perfect ❤️

thanks 🙏🏼

**Comment by magicmatatjahu** [comment]
@derberg Thanks! Could you accept again? I had to resolve conflicts.

**Review by derberg — APPROVED** [review]

**Pull request merged**
